# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.21.7
yarn_mappings=1.21.7+build.6
loader_version=0.16.13

# Mod Properties
mod_version=1.0.0
maven_group=me.ellieis
archives_base_name=sabotage

# Dependencies
fabric_version=0.128.2+1.21.7
plasmid_version=0.6.5+1.21.7